name: MacOS

on:
  push:
    branches: [ master, test ]
  pull_request:
    branches: [ master, test ]

jobs:
  build:
    runs-on: macos-15
    strategy:
      matrix:
        BUILD_TYPE: [Debug, Release]

    steps:
    - name: Checkout repository and submodule
      uses: actions/checkout@v7
      with:
        submodules: recursive

    - name: Install dependencies
      run: brew install glew glfw

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_CXX_FLAGS=-Wno-undefined-inline -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -VV -C ${{matrix.BUILD_TYPE}} --rerun-failed --output-on-failure

    - name: Prepare archive
      run: |
        mkdir archive-${{matrix.BUILD_TYPE}}
        cp "${{github.workspace}}/build/app/gui/irritator-0.1" archive-${{matrix.BUILD_TYPE}}/irritator
        tar -czf irritator-macos-${{matrix.BUILD_TYPE}}.tar.gz -C archive-${{matrix.BUILD_TYPE}} irritator

    - name: Upload archive
      uses: actions/upload-artifact@v7
      with:
        name: irritator-macos-${{matrix.BUILD_TYPE}}
        path: irritator-macos-${{matrix.BUILD_TYPE}}.tar.gz